import Head from 'next/head';
import Banner from '../components/Banner';
import Card from '../components/Card';
import stores from '../Data/coffee.json';

export const getStaticProps = async () => {
	return {
		props: {
			stores,
		},
	};
};

export default function Home(props) {
	const bannerBtnClick = () => {
		alert('Banner button clikcked!');
	};

	return (
		<div className=" bg-bgMain min-h-screen object-cover">
			<Head>
				<title>Udemy Coffee Shop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header>
				<Banner btnText={'View Stores By you'} handleOnClick={bannerBtnClick} />
			</header>

			<main className="p-5">
				{props.stores.length > 0 && (
					<section>
						<h1 className="text-4xl underline text-amber-900 font-bold mb-6">
							Random Coffee Shops
						</h1>
						<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4">
							{props.stores.map((store) => (
								<Card
									key={store.id}
									href={`/coffee-shops/${store.name}`}
									name={store.name}
									imgUrl={store.imgUrl}
									address={store.address}
									city={store.city}
								/>
							))}
						</div>
					</section>
				)}
			</main>
		</div>
	);
}
